### PR TITLE
Option to display objective changes automatically or not.

### PR DESCRIPTION
**Pull request by Zalewa**

### CODE REVIEW

**Comment by akarnokd** [comment]
Could you explain the reason behind this change? Also the sound notification doesn't play either, is this intentional?

**Comment by Zalewa** [comment]
> Could you explain the reason behind this change?

The main reason is that getting objective popups during the game has become very annoying for me. I wanted an option to hide them but couldn't find one. In addition I also don't remember the original game having any objective indicator. Last time I played the original was a very long time ago so I may not remember correctly, though.

List of objective is a nice addition as people can get stuck in this game. I remember that everyone in my family had problems with Garthog level where the game hasn't made it clear enough that to progress you need to kill the Garthogs. The constant popups are nagging though, especially since in many cases you can infer what to do simply basing on what is happening on the starmap.

> Also the sound notification doesn't play either, is this intentional?

If that was the case in the original game then yes, it was intentional. Perhaps this setting could be changed into a tri-state setting with "Yes", "No" and "Sound Only" options.

**Comment by akarnokd** [comment]
There were no objectives indicator in the original game and many people I talked to or forums I saw about the game complained they didn't really know what to do. 

Let's have this as on/off for now but could you verify this doesn't break scripting (at least on level 1)? I sometimes tied scripted events to audio and visual state, but I don't remember exactly now.

**Comment by Zalewa** [comment]
> Many people I talked to or forums I saw about the game complained they didn't really know what to do.

That's why the option is on by default and why the list should be accessible manually at all times.

> Could you verify this doesn't break scripting (at least on level 1)

I just tested and successfully managed to get fired by Commander Moustache at level 1 by neglecting ship protection objectives. I also managed to beat level 1 at normal difficulty.

**Comment by akarnokd** [comment]
Great!

**Pull request merged**
