### PR TITLE
Add new shortcuts and a fix

### PR DESCRIPTION
**Pull request by deejayy**
- `DELETE` for destroy the selected building
- `CTRL+DELETE` to remove all buildings at once (except Commnuity Hub)
- `U` to upgrade selected building 1 level
- `CTRL+U` to upgrade selected building to max level
- `CTRL+SHIFT+U` to upgrade all buildings to max level
- fix: don't allow a upgrade while construction in progress
- workaround: don't overwhelm the user with the sound effects when multiple building destruction happens at the same time

Code may be shitty, I don't know Java ;] feel free to adjust if needed || let me know.

### CODE REVIEW

**Comment by hemoridos** [comment]
How about `U` for upgrade one level, and `CTRL+U` for max level.

**Comment by hemoridos** [comment]
I'm not sure about the use case of the `CTRL+DELETE` feature. It removes the next building on the planet in some order. The only use case I see for it, is to remove everything with the exception of the Colony Hub. If that is the case then, it instead could be a single button press that removes everything, except the Colony Hub.

**Comment by deejayy** [comment]
> How about U for upgrade one level, and CTRL+U for max level.

yup, thought about that, I need to add some safeties (like don't allow another upgrade while an upgrade is in progress)

> I'm not sure about the use case of the CTRL+DELETE feature.

it's because I couldn't manage :D I don't have the full visibility on the architecture yet, and iterating thru the buildings wasn't working (I have a guess on the reason, but haven't checked). Meanwhile, I looked around a bit, so I might be able to solve it.

**Comment by deejayy** [comment]
Also, these things are working in a not-owned planet or in combat, so definitely some extra checks need to be added (to not be a cheat).

**Comment by hemoridos** [comment]
For checking the building demolition a simple statement is enough
 if (planet().owner == player() && battle == null) {
  do stuff
 }

Iterators won't work for removing elements from the underlying list/array.
For iterating through the buildings you could use a construct like so
for(Building b : new ArrayList<>(surface().building) {
 ... do the things...
}

**Comment by deejayy** [comment]
```java
for(Building b : new ArrayList<>(surface().buildings.list())) {
    if (!b.type.kind.equals(BuildingType.KIND_MAIN_BUILDING)) {
        doSelectBuilding(b);
        doDemolish();
    }
}
```

this did the trick.

now addressing the upgrade suggestions :)

**Comment by deejayy** [comment]
Also added owner and battle constraints!

**Comment by deejayy** [comment]
Thinking of two things:

- `DELETE for destroy the selected building` < one button is easy to press, it may be annoying, what about changing it to CTRL+DELETE instead?
- `CTRL+DELETE to remove all buildings at once (except Commnuity Hub)` - correspondingly, turn this into CTRL+SHIFT+DELETE, aligning with the upgrade-all-to-max shortcut? (CTRL+SHIFT+U) - so "CTRL+SHIFT+" will mean planet-wide actions consistently.

- prevent accidental delete of the Main Building via shortcut and only allow it from the UI with well positioned mouse click

**Comment by akarnokd** [comment]
Hozzáadtam az eszköztippekhez is a billentyűket:

image

image

**Comment by deejayy** [comment]
Yaaay! Köszi, el is feledtem!

**Pull request merged**
