### PR TITLE
Spacewar projectile updates.

### PR DESCRIPTION
**Pull request by hemoridos**
- Modified aiming of weapons, added intentional randomness while taking into account the target's orientation and shape.
- Added some randomness to the fire rate of weapons, this brakes up the monotonousness when multiple ship fire the same weapons at the time.
- Restored the pixel perfect hit detection code. I've seen some performance degradation but seemed negligible to the overall spacewar scene.

Originally for random accuracy I tried using to simply get a a random position in the rectangle encompassing the target's image, but that gave unfair advantage to elongated ships(like most empire ships) when facing the enemy.
I ended up creating a method that more or less follows the shape and orientation of the target. When the space objects are loaded at the start, a rectangle size is calculated that is encompassing the trimmed images of the object. This rectangle is then used when aiming at targets. First get a random point in that rectangle then rotate the point around the object's center to follow the orientation of the target image and use that point as on offset when aiming. This of course has little effect on objects that fit in a square.
(Maybe using an oval area based on the trimmed rectangle to get the random point could work better.)

Here's a video showing this with the Thorin, the green dots used for debugging are showing the positions projectiles are aiming at:
[Thorin test](https://drive.google.com/file/d/1s2JqFRFvmW3-mXKM7g4RG6wTNQLiZnQI/view?usp=drive_link
)

I also added some fluctuation to the weapon delays when firing. This gives it more "realistic(?)" feeling that was missing in open-ig. When a weapon fires a  random multiplier between 0.5-1.5 is applied to the cooldown. I tried smaller ranges but they did not have the desired effect.
Some videos to illustrate:
[Original for reference](https://drive.google.com/file/d/1qmnSI0prhofrnh2_rZhvI94Nu4LgJ_ZP/view?usp=drive_link
)
[This PR](https://drive.google.com/file/d/17H_YhXnE_997BSxj21Ty1n6aarLk7iUG/view?usp=drive_link
)
[OpenIG-master](https://drive.google.com/file/d/1hENVsaYZpH18rCMD_nK8WAIPzqbO9-36/view?usp=drive_link)

Some additional videos with no sound:
[Large battle this PR(with debug dots)](https://drive.google.com/file/d/1vpObfZalF6eevWqU9NXBJHOtPtntRFir/view?usp=drive_link)
[Large battle OG IG](https://drive.google.com/file/d/1upIh6sQYdgClCVdL2ZNw-CUdkIzZIKZI/view?usp=drive_link)

### CODE REVIEW

**Comment by hemoridos** [comment]
Also this should make #333 effectively resolved.

**Comment by akarnokd** [comment]
I need permission to view the videos.

**Comment by hemoridos** [comment]
Sorry, corrected it should open now.

**Comment by akarnokd** [comment]
Thanks for tackling these.

Are you working on something else right now? If not, I'd like to release these latest changes.

**Pull request merged**
